### ISSUE TITLE
Issue with downloading trained model

### ISSUE THREAD

**Issue by mrdupadupa** [YuweiYin/CROP#2]
I want to use the project for my own research. For that, I have to download the trained Roberta model from (https://pan.baidu.com/s/1YQjJEIVevEHXk-wpxcA8wg?pwd=jp4b). However, I cannot download that because I need to register and to register I have to have a Chinese phone number, which is impossible because I am not Chinese and/or in China . Can you please upload it to some resources available without registration e.g. a Google Drive?

**Comment by YuweiYin** [comment]
Thanks for your interest! We will provide a Google Drive option and update the README doc soon.
